# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #time, velocity, angular vel
  - [1.233, 0.43, 0.001]
  - [1.65, 0.43, 4.59] #[1.8, 0.43, 2.896]
  - [0.65, 0.43, 0.0]
  - [0.65, 0.43, 0.0]
turn_right:
  - [0.565, 0.43, 0] #[0.6, 0.43, 0]
  - [1.25, 0.43, -4.77] #[1.2, 0.3, -4.506]
  - [0.0, 0.43, 0.0]
  - [0.25, 0.43, 0.0]
turn_forward:
  - [0.4, 0.43, 0.0]
  - [1.5, 0.43, 0.0]
  - [0.0, 0.43, 0.0]
  - [0.5, 0.43, 0.0]
# turn_stop:
#   - [0.2, 0.0, 0.0]

#do we want to update the values based on where/what angle we stop at.
trajectory_reparam: 1
